#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
set -x
max_memory_bytes=`oo-cgroup-read memory.limit_in_bytes`
max_memory_mb=`expr $max_memory_bytes / 1048576`
CASSANDRA_JVM_HEAP_RATIO=0.5
CASSANDRA_JVM_HEAP_NEWSIZE=0.25
max_heap_size_in_mb=$( echo "$max_memory_mb * $CASSANDRA_JVM_HEAP_RATIO" | bc | awk '{print int($1+0.5)}')
heap_newsize_in_mb=$( echo "$max_memory_mb * $CASSANDRA_JVM_HEAP_NEWSIZE" | bc | awk '{print int($1+0.5)}')
MAX_HEAP_SIZE="${max_heap_size_in_mb}M"
HEAP_NEWSIZE="${heap_newsize_in_mb}M"
export MAX_HEAP_SIZE
export HEAP_NEWSIZE
# set JAVA_HOME and JAVA_PATH for java_8
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk1.8.0_05"
export PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin:$PATH
cd $OPENSHIFT_DATA_DIR/cassandra
bin/cassandra |& /usr/bin/logshifter -tag classcarddbsessions &
export CQLSH_HOST=$OPENSHIFT_DIY_IP
export CQLSH_PORT=19160
sleep 30
